### ISSUE TITLE
Custom python installations

### ISSUE THREAD

**Issue by LightningWB** [extremeheat/JSPyBridge#21]
I'm planning on using this to make a python plugin api but I noticed you have to use python from the windows store. Is there anyway to set a path to a python installation, so I can bundle python with my project? Thanks.

**Comment by extremeheat** [comment]
Are you referring to the pythonia bridge on npm or the javascript bridge on pip? They both will use node.js/python off of the system path, which you can adjust as an environment variable.

**Comment by LightningWB** [comment]
sorry, I should've mentioned I'm calling python from nodejs, but when I install python from the https://www.python.org/downloads/, I only get python and not python3.  An option to just set the absolute path would avoid messing with the path too much. I could make a pr to default `3` to `python3`, `2` to `python2` and anything else as a direct path.

**Comment by extremeheat** [comment]
OK, at the moment the Python process is asynchronously started at import time so any configuration would probably have to happen through an environment flag. The python3/python binary issue could probably be fixed by catching an ENOENT error and falling back to Python 2.

**Comment by extremeheat** [comment]
Should be fixed in 0.2.10, it adds a new `PYTHON_BIN` env var check when starting the Python process. If not specified, it fallsback to python3 from $PATH then just python. Please re-open if it's still an issue.

You can add the env var from node.js by setting `process.env.PYTHON_BIN = '/path/to/python.exe'` before you import `pythonia`.
