### ISSUE TITLE
Respond with JavaScript function result

### ISSUE THREAD

**Issue by janober** [extremeheat/JSPyBridge#66]
Hello,

I am sadly stuck again. I have to give access to quite a lot of data to the code in Python. So it is made available via special methods. It seems to work fine in Python. If I execute the code below, it will print in Python correctly `{ b: 123 }`.
When I however directly return it, then I get an error. For some reason I get another error when I follow what the first one recommends 

Thanks a lot for your help!

Here is the code to easily reproduce the issue I am facing:
```javascript
const { python, builtins } = require('pythonia');

async function main() {
	const testData = {
		a: () => {
			return {
				b: 123,
			};
		},
	};

	let response = undefined;

	const callback = (data) => {
		response = data;
	};

	await builtins.exec(
		`def main():
	print(testData['a']());
	return testData['a']()
callback(main())
`,
		{
			callback,
			testData,
		},
	);

	console.log('test1');
	console.log(response);
	// Expected:
	//    { b: 123 }
	// Actual response:
	//    (Some Python object) Use `await object.toString()` to get this object's repr().

	console.log('test2');
	console.log(await response.toString());
	// ERROR:
	// Python Error  Call to '' failed:
}
main().then(() => python.exit());

```

**Comment by extremeheat** [comment]
JSPyBridge is largely intended for importing and calling libraries between the two languages. Single files can also be imported with the `require` or `python.import` functions. What you're doing with `exec` here is about the same as writing the Python script to a file and then `python.import`ing it. I don't advise using it as an arbitrary code execution environment as it's not much different than using eval() from in Node.js, except with the added overhead of bridging to Python.

The issue here with your code seems to be related to garbage collection handling. Converting the JS proxy object to a Python native one should fix, 
```js
await builtins.exec('cb(testData["a"]().valueOf())', { cb, testData })
```

And in the JS side callback,
```js
var cb = async data => { let a = await data.valueOf(); console.log('cb', a) }
```

**Comment by janober** [comment]
Amazing, thanks a lot for your help. Works perfectly.
